apiVersion: v1
kind: ConfigMap
metadata:
  name: marea-config
  namespace: marea
data:
  NODE_ENV: "production"
  PORT: "5000"
  DATABASE_HOST: "marea-db-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "marea_db"
  DATABASE_USER: "marea"
---
apiVersion: v1
kind: Secret
metadata:
  name: marea-secret
  namespace: marea
type: Opaque
stringData:
  DATABASE_PASSWORD: "marea_secret_2026"
  DATABASE_URL: "postgres://marea:marea_secret_2026@marea-db-service:5432/marea_db"
